apiVersion: v2
name: nexops
description: A Helm chart for NexOps - DevOps Operations Center
type: application
version: 1.3.0
appVersion: "1.3.0"
keywords:
  - kubernetes
  - dashboard
  - devops
  - monitoring
  - security
home: https://github.com/gauravtayade11/nexops
sources:
  - https://github.com/gauravtayade11/nexops
maintainers:
  - name: Gaurav Tayade
    url: https://github.com/gauravtayade11
icon: https://raw.githubusercontent.com/gauravtayade11/nexops/main/docs/images/logo.png
